config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :topics

  resources :users do
    scope module: "users" do
      resources :posts
      resources :topics
    end
    get "pph", on: :member
    get "ppdow", on: :member
    get "pphod", on: :member
  end

  get "sessions/new" => "sessions#new", as: :new_session
  post "sessions" => "sessions#create", as: :sessions
  delete "user/session" => "sessions#destroy", as: :session

  get "passwords/new" => "passwords#new", as: :new_password
  post "passwords" => "passwords#create", as: :passwords
  get "user/password/edit" => "passwords#edit", as: :edit_password
  put "user/password" => "passwords#update", as: :password
  patch "user/password" => "passwords#update"

  get "rankings" => "rankings#index"
  get "search" => "search#index"

  get "stats" => "stats#index"
  get "stats/pph" => "stats#pph"
  get "stats/ppdow" => "stats#ppdow"
  get "stats/pphod" => "stats#pphod"

  root "topics#index"
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{charset: "utf-8"}
    %title= title
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #header-outside
      #header-inside
        %h1
          = link_to root_path do
            = image_tag "header-left.png", width: 496, height: 79, alt: "sedemnajst.si"
        .clear
        #search
          = form_tag search_path, method: :get do
            = text_field_tag :q, params[:q], size: 25
            = submit_tag "išči"
    #nav
      #nav-site
        = link_to "arhiv", root_path
        |
        = link_to "dogajanje", stats_path
        |
        = link_to "kralji gnoja", rankings_path
        |
        = link_to "uporabniki", users_path
      #nav-user
        = @current_user
        (
        %span>= link_to "odjava", session_path, method: :delete
        )
      .clear
    = yield
    #footer
      %p= archive_status_text

app/views/layouts/noauth.html.haml
!!! 5
%html
  %head
    %meta{charset: "utf-8"}
    %title= title
    = stylesheet_link_tag "noauth", media: "all"
    = javascript_include_tag "noauth"
    = csrf_meta_tags
  %body
    .section
      %h1.section-heading= content_for :heading
      - if alert
        %p.alert= alert
      - if notice
        %p.notice= notice
      .section-content= yield